     name: SRKVerse CI

     on:
       push:
         branches: [main, 1.0]
       pull_request:
         branches: [main, 1.0]

     jobs:
       test:
         runs-on: ubuntu-latest
         services:
           postgres:
             image: postgres:13
             env:
               POSTGRES_DB: srkverse
               POSTGRES_USER: postgres
               POSTGRES_PASSWORD: password
             ports:
               - 5432:5432
             options: >-
               --health-cmd pg_isready
               --health-interval 10s
               --health-timeout 5s
               --health-retries 5
           redis:
             image: redis:7
             ports:
               - 6379:6379
         steps:
           - uses: actions/checkout@v4
           - name: Set up Python
             uses: actions/setup-python@v5
             with:
               python-version: '3.9'
           - name: Install dependencies
             run: |
               python -m pip install --upgrade pip
               pip install -r SRKVerse/requirements.txt
           - name: Run migrations
             env:
               DB_NAME: srkverse
               DB_USER: postgres
               DB_PASSWORD: password
               DB_HOST: localhost
               DB_PORT: 5432
               REDIS_URL: redis://localhost:6379/1
             run: python manage.py migrate
           - name: Run tests
             env:
               DJANGO_SECRET_KEY: test-secret-key
               REDIS_URL: redis://localhost:6379/1
               SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
               SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
             run: python manage.py test

       test-spotify-live:
         runs-on: ubuntu-latest
         if: github.event_name == 'push'
         services:
           postgres:
             image: postgres:13
             env:
               POSTGRES_DB: srkverse
               POSTGRES_USER: postgres
               POSTGRES_PASSWORD: password
             ports:
               - 5432:5432
             options: >-
               --health-cmd pg_isready
               --health-interval 10s
               --health-timeout 5s
               --health-retries 5
           redis:
             image: redis:7
             ports:
               - 6379:6379
         steps:
           - uses: actions/checkout@v4
           - name: Set up Python
             uses: actions/setup-python@v5
             with:
               python-version: '3.9'
           - name: Install dependencies
             run: |
               python -m pip install --upgrade pip
               pip install -r requirements.txt
           - name: Run migrations
             env:
               DB_NAME: srkverse
               DB_USER: postgres
               DB_PASSWORD: password
               DB_HOST: localhost
               DB_PORT: 5432
               REDIS_URL: redis://localhost:6379/1
             run: python manage.py migrate
           - name: Run live Spotify tests
             env:
               DJANGO_SECRET_KEY: test-secret-key
               REDIS_URL: redis://localhost:6379/1
               SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
               SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
               RUN_SPOTIFY_LIVE_TESTS: true
             run: python manage.py test api.tests.SpotifyIntegrationTests.test_enhance_song_with_spotify_real
