   name: Deploy SRKVerse

   on:
     push:
       branches: [main]

   jobs:
     deploy:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v4
         - name: Set up Python
           uses: actions/setup-python@v5
           with:
             python-version: '3.9'
         - name: Install dependencies
           run: |
             python -m pip install --upgrade pip
             pip install -r requirements.txt
         - name: Deploy to AWS EC2
           env:
             SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
             EC2_HOST: ${{ secrets.EC2_HOST }}
             EC2_USER: ${{ secrets.EC2_USER }}
           run: |
             echo "$SSH_PRIVATE_KEY" > private_key.pem
             chmod 600 private_key.pem
             ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
               cd /path/to/srkverse
               git pull origin main
               source venv/bin/activate
               pip install -r requirements.txt
               python manage.py migrate
               python manage.py collectstatic --noinput
               sudo systemctl restart gunicorn
             EOF
         - name: Upload frontend to S3
           env:
             AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
             AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
             AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
           run: |
             pip install awscli
             aws s3 sync ./frontend/ s3://$AWS_STORAGE_BUCKET_NAME/frontend/ --delete